# Generated by Django 3.2.3 on 2023-03-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastelitos', '0002_cliente_proveedor_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='num_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='num_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
