# Generated by Django 3.2.3 on 2023-03-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastelitos', '0004_alter_sucursal_num_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
