# Generated by Django 3.2.3 on 2023-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastelitos', '0005_alter_cliente_num_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='num_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
