# Generated by Django 3.2.3 on 2023-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=20)),
                ('descripcion', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cliente_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=20)),
                ('apellido', models.CharField(default=None, max_length=70)),
                ('codigo_postal', models.IntegerField()),
                ('calle', models.CharField(default=None, max_length=100)),
                ('colonia', models.CharField(default=None, max_length=100)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.CharField(default=None, max_length=20)),
                ('ciudad', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='empleado_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=20)),
                ('apellido', models.CharField(default=None, max_length=70)),
                ('codigo_postal', models.IntegerField()),
                ('calle', models.CharField(default=None, max_length=100)),
                ('colonia', models.CharField(default=None, max_length=100)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.CharField(default=None, max_length=20)),
                ('ciudad', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=20)),
                ('precio', models.FloatField(default=None)),
                ('categoria', models.CharField(default=None, max_length=40)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default=None, max_length=70)),
                ('codigo_postal', models.IntegerField()),
                ('calle', models.CharField(default=None, max_length=100)),
                ('colonia', models.CharField(default=None, max_length=100)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.CharField(default=None, max_length=20)),
                ('ciudad', models.CharField(default=None, max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sucursal_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.IntegerField()),
                ('calle', models.CharField(default=None, max_length=100)),
                ('colonia', models.CharField(default=None, max_length=100)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.CharField(default=None, max_length=20)),
                ('ciudad', models.CharField(default=None, max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
