# Generated by Django 3.2.3 on 2023-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_r',
            name='descuento',
            field=models.FloatField(default=None),
        ),
    ]
