# Generated by Django 3.2.3 on 2023-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_producto_r_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_r',
            name='descuento',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
